name: premier_league
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase - nur dieses Paket ist nÃ¶tig
  supabase_flutter: ^2.8.4

  # Andere Pakete
  http: ^1.3.0
  provider: ^6.1.2
  intl: ^0.20.2
  pool: ^1.5.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  # Firebase
  #firebase_core: ^3.12.1
  #cloud_firestore: ^5.6.5

  # UI
  cupertino_icons: ^1.0.6
  cupertino_http: ^2.3.0
  cronet_http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
